language: java
jdk:
- oraclejdk8
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_install:
- openssl aes-256-cbc -K $encrypted_428d7cee0894_key -iv $encrypted_428d7cee0894_iv -in src/main/resources/google_sheets_credentials.json.enc -out src/main/resources/google_sheets_credentials.json -d
install:
- "./gradlew assemble --stacktrace"
before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: redi-project-tenjin@googlegroups.com
  password:
    secure: j+Z7E9aBfDI5I7rtii8FjxKfXTuc3HuvuGqNu1LzA2dsRgy8+P7e95A8UEXR4olw4qAdNLAuuc5LDwII4O12UIKh97GeWvIQNF55xfm7+HVoEauL52cajPQXGAgyAkRx7JQItBVBct1ArM3C35zC2OfnrsfWg0NcM+oPHFovmz6Fqp452yt4YaRA7MTRoKnqYfJUDkEb5s0V6S0i0Xkz5vwDEszuGHz1H1FndQnoGJ1FaX21gyDvKfV2ACWcCMDUmVjPjwAkoG3+qpfxMh59Fey12qYlwLgod2XZzwkMciO3k6MIMDU/zRIInriE/6WXShBWVGkyLQpme1sQ1KoH1oiNrIS9UcVaiHFYPJMoBUjmPcsCtzNKonTIqno3DWSn4Sx6uB3t+tJYmlNNEtBSzaCzmHADsK/qmDZt7NeslcEZ8cfQjx0MAmQxSErtThYoTU5lGHXuLnsgTmfpmBk+ea+bhFHzzsOjSDfRUWEo/afX4TIfVQ7IF3WN3ij1VUg4wk9cRfetr7knXyJVI0Z0OCbzjdsEpPUuk1rfXJqe2OhaKe5Wwp/NJoM0kWlSvvOiI6GXD9aOMrSiRsi+K/Z3ji5R8Dj29GbW5LEWDofNnjJSAmiIC0yr+GWpcoTfHywa77abupQUsORE3IZU70EMXXKaBZGg1CYTO/gsXxK7r4w=
  organization: tenjin
  space: development
