language: java
jdk:
- oraclejdk9
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_install:
- openssl aes-256-cbc -K $encrypted_428d7cee0894_key -iv $encrypted_428d7cee0894_iv
  -in src/main/resources/google_sheets_credentials.json.enc -out src/main/resources/google_sheets_credentials.json
  -d
- openssl aes-256-cbc -K $encrypted_428d7cee0894_key -iv $encrypted_428d7cee0894_iv
  -in src/main/resources/google_sheets_acceptance_credentials.json.enc -out src/main/resources/google_sheets_acceptance_credentials.json
  -d
- openssl aes-256-cbc -K $encrypted_428d7cee0894_key -iv $encrypted_428d7cee0894_iv
  -in src/main/resources/application-production.yml.enc -out src/main/resources/application-production.yml
  -d
- openssl aes-256-cbc -K $encrypted_428d7cee0894_key -iv $encrypted_428d7cee0894_iv
  -in src/main/resources/application.yml.enc -out src/main/resources/application.yml
  -d
- openssl aes-256-cbc -K $encrypted_428d7cee0894_key -iv $encrypted_428d7cee0894_iv
  -in src/test/resources/application.yml.enc -out src/test/resources/application.yml
  -d
jobs:
  include:
#  - stage: test
#    script: "./gradlew clean build"
  - stage: deploy to acceptance
    script: skip
    deploy: &heroku
      provider: heroku
      api_key:
        secure: KBw8XRV11uJ3Su8mTBA4dFw797bNZ2xutmW2fXdK1GmQoY6GNQ7v3VnpS9ZBK7PMN3fVMO/4UcLcITU2v2wSqHb2/JdY1N6NP+4zPR3uwtWOqTNVI2l40Zh6+Ez8FroxTRi+kdfyKKtDArL7vmLh8U/PO7w9o+PcKFvY7tL3oVNBx7VOXYCmYR7PcjOTFg0Gi+DxHkA+vJ7KjC3A4BVHaPCNuECht/t4D43DCe2Cn8VpccHUgTra9QRk8Zel26O6/IjznlK16ySo66AqhTxI8rpRp2av7GXblnoe1O0gLK7IZzsDYr/De5ug39ftfQAwBGbe3Lfe+0pBX1eOfWDuzRlitBqrKBb2y0Zz3RpHBYT0A1QxAaN+NnDhi3uvPMJCIZ7PUF/PK3gp4jkRL3gqBZCd2tVputT94z//4U3JII8QkZlir2b8uQ1wT1tD1Sj3GHCcY615NER1LtmFstSDE8m9WsZ3B9QlVK/660oLFC7evz5P9NmV0ByR5CGAz2qJFExqJ7CmOiK0WYPF8Go+HdKTlXwz1M53Nm0PrstO4QIXXJ49u9LMQi6TD8WE89tvGRmNHY5Bac1KqmcTz5Lj/kmhL6YasUB0JCR22uJ2JOqPyy5vnmVgaWOsRZQ9H64KX2BjJ62K0gEpe1hs0mRaRb8y3cElB/Wu04ncMMtld3M=
      app: project-tenjin-staging
  - stage: deploy to production
    script: skip
    deploy:
      <<: *heroku
      app: project-tenjin-production
