name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Buil tester
      run: docker build . --file Dockerfile --target tester --tag backend:${{ github.event.workflow_run.head_sha }}
    
    - name: Test
      run: docker run --name backend-tester --rm backend:${{ github.event.workflow_run.head_sha }}

    - name: Build runner
      run: docker build . --file Dockerfile --target runner --tag backend:$(date +%s)      
